services: docker

git:
  depth: false

install: make docker-login build-docker

stages:
- name: test
- name: publish-docker

jobs:
  include:
  - stage: test
    name: Publish docker image
    script:
    - make run-docker
  - stage: publish
    name: Publish docker image
    script:
    - make docker-login publish-docker
